### ISSUE TITLE
Hello,I have a question in the 'target assignment'?

### ISSUE THREAD

**Issue by BCWang93** [DeNA/PyTorch_YOLOv3#4]
I have a question in the 'target assignment'. You use the 'truth_box' and 'ref_anchors' to calculate the ious.But you use nine anchors.I think it should three.Why do you use nine?I can't understand it.Can you help me.Thanks!Thank you very much

**Comment by hirotomusiker** [comment]
It's a good question - yes we compare truth boxes with nine anchors.
There are three yolo layers which are responsible for different scales.
Each ground truth box must be assigned to ONLY ONE anchor across the scales.
If you use three anchors at each yolo layer, a ground truth box is assigned to MULTIPLE (three) anchors.

What we do for one certain target box at one yolo layer is:
- calculate IoUs between the box and nine anchors across three scales
- assign the box to the anchor that has the maximum IoU only if the anchor belongs to the yolo layer using anch_mask
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/models/yolo_layer.py#L141-L142

The original implementation (darknet) does the same.
It's not efficient because we do the same calculation three times, but it's not a complex calculation and the computation time is - I believe - negligible.

**Comment by BCWang93** [comment]
> It's a good question - yes we compare truth boxes with nine anchors.
> There are three yolo layers which are responsible for different scales.
> Each ground truth box must be assigned to ONLY ONE anchor across the scales.
> If you use three anchors at each yolo layer, a ground truth box is assigned to MULTIPLE (three) anchors.
> 
> What we do for one certain target box at one yolo layer is:
> 
> * calculate IoUs between the box and nine anchors across three scales
> * assign the box to the anchor that has the maximum IoU only if the anchor belongs to the yolo layer using anch_mask
>   https://github.com/DeNA/PyTorch_YOLOv3/blob/master/models/yolo_layer.py#L141-L142
> 
> The original implementation (darknet) does the same.
> It's not efficient because we do the same calculation three times, but it's not a complex calculation and the computation time is - I believe - negligible.

@hirotomusiker  Thanks for your reply! I always think one 'grid_ceil' has three 'anchors'.So I think in every scale yolo_layer should has three 'anchors'.I didn't notice the code（https://github.com/DeNA/PyTorch_YOLOv3/blob/master/models/yolo_layer.py#L141-L142）just now.Because in others replement is always three anchors  to calculate the 'iou' in every scale yolo_layer.Now I know they are equivalent. Thank you very much!

**Comment by hirotomusiker** [comment]
Actually one grid cell has three anchors. (3 anchors * 85 channels) 
I use nine anchors only for IoU calculation and filter it afterwards. Thank you!
