### ISSUE TITLE
training our data

### ISSUE THREAD

**Issue by Codermay** [DeNA/PyTorch_YOLOv3#8]
hello, I want to trian the network using my data .But I don not kown how to do that. Could you make a complaint for this problem. Thank you!!

**Comment by hirotomusiker** [comment]
Thank you for using our repo!
I would like give some suggestion for your issue.

In order to train the network on your own data, you have to change cocodataset.py to your own dataset class.
(I will move the following instruction to readme later)

### Initialization of the dataset class
You can change the following part so that the dataset class can load your dataset.
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/dataset/cocodataset.py#L29-L41
You need:
1. list of data ids
The cocodataset class has the list of image ids  - self.ids. You have to create an id list of your dataset.
2. annotation data
We use pycocotools that loads the json annotation file into memory during initialization.
You will have to load the annotation data of your dataset on self.annotation for example.

### __getitem__ part of the dataset class

1. load an image
Change the following lines so that you can load an image of you dataset corresponding to the selected id_ . 
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/dataset/cocodataset.py#L72-L73

2. load annotations
Change the following lines so that you can load the annotations corresponding to the id_ . 
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/dataset/cocodataset.py#L68-L69
https://github.com/DeNA/PyTorch_YOLOv3/blob/master/dataset/cocodataset.py#L87-L90
The annotation data should be imported into 'labels' list. Each element of 'labels' consists of [class, x1, y1, x2, y2] where \
                class (float): class index.
                x1, y1, x2, y2 (float) : coordinates of left-top and right-bottom points of bounding boxes.
                    Values range from 0 to width or height of the image.

**Comment by Codermay** [comment]
Thank you for your reply. And I have a question. Have you trained this model for COCO dataset. I want to know the results. Because I can not find the good implement of YOLOV3 by pytorch.  And expect for your updata.

**Comment by hirotomusiker** [comment]
Please look at README for our training results on COCO.
Yes it’s very hard to find an implementation with reproduced training performance.
But I believe ours can reproduce the darknet’s training. I have prepared the final data augmentation at this branch and will report the training results with the new feature. 
https://github.com/DeNA/PyTorch_YOLOv3/tree/feature/add_random_distortion
Thank you!
